const initialOnis = [
    {
        x:4,
        y:12,
        pathIndex: 0,
        pathDirection : 1,
        direction: 'back',
        dead: false,
        path: [
            {x:4,y:12, direction:'right'},
            {x:5,y:12, direction:'right'},
            {x:6,y:12, direction:'right'},
            {x:7,y:12, direction:'right'},
            {x:8,y:12, direction:'right'},
            {x:9,y:12, direction:'right'},
            {x:8,y:12, direction:'left'},
            {x:7,y:12, direction:'left'},
            {x:6,y:12, direction:'left'},
            {x:5,y:12, direction:'left'},
            {x:4,y:12, direction:'left'},
        ],
    },
    {
        x:11,
        y:12,
        pathIndex: 0,
        pathDirection : 1,
        dead: false,
        path: [
            {x:11,y:12, direction:'front'},
            {x:11,y:11, direction:'front'},
            {x:11,y:10, direction:'front'},
            {x:12,y:10, direction:'right'},
            {x:13,y:10, direction:'right'},
            {x:13,y:11, direction:'back'},
            {x:13,y:12, direction:'back'},
            {x:12,y:12, direction:'left'},
            {x:11,y:12, direction:'left'},
        ],
    },
    {
        x:3,
        y:8,
        pathIndex: 0,
        pathDirection : 1,
        dead: false,
        path: [
            {x:3,y:8, direction:'right'},
            {x:4,y:8, direction:'right'},
            {x:5,y:8, direction:'right'},
            {x:6,y:8, direction:'right'},
            {x:7,y:8, direction:'right'},
            {x:8,y:8, direction:'right'},
            {x:9,y:8, direction:'right'},
            {x:10,y:8, direction:'right'},
            {x:11,y:8, direction:'right'},
            {x:10,y:8, direction:'left'},
            {x:9,y:8, direction:'left'},
            {x:8,y:8, direction:'left'},
            {x:7,y:8, direction:'left'},
            {x:6,y:8, direction:'left'},
            {x:5,y:8, direction:'left'},
            {x:4,y:8, direction:'left'},
            {x:3,y:8, direction:'left'},
        ],
    },
    {
        x:3,
        y:5,
        pathIndex: 0,
        pathDirection : 1,
        dead: false,
        path: [
            {x:3,y:5, direction:'right'},
            {x:4,y:5, direction:'right'},
            {x:5,y:5, direction:'right'},
            {x:6,y:5, direction:'right'},
            {x:7,y:5, direction:'right'},
            {x:8,y:5, direction:'right'},
            {x:9,y:5, direction:'right'},
            {x:10,y:5, direction:'right'},
            {x:11,y:5, direction:'right'},
            {x:12,y:5, direction:'right'},
            {x:13,y:5, direction:'right'},
            {x:12,y:5, direction:'left'},
            {x:11,y:5, direction:'left'},
            {x:10,y:5, direction:'left'},
            {x:9,y:5, direction:'left'},
            {x:8,y:5, direction:'left'},
            {x:7,y:5, direction:'left'},
            {x:6,y:5, direction:'left'},
            {x:5,y:5, direction:'left'},
            {x:4,y:5, direction:'left'},
            {x:3,y:5, direction:'left'},
        ],
    },
    {
        x:3,
        y:2,
        pathIndex: 0,
        pathDirection : 1,
        dead: false,
        path: [
            {x:3,y:2, direction: 'right'},
            {x:4,y:2, direction:'right'},
            {x:5,y:2, direction:'right'},
            {x:6,y:2, direction:'right'},
            {x:7,y:2, direction:'right'},
            {x:8,y:2, direction:'right'},
            {x:9,y:2, direction:'right'},
            {x:10,y:2, direction:'right'},
            {x:11,y:2, direction:'right'},
            {x:12,y:2, direction:'right'},
            {x:13,y:2, direction:'right'},
            {x:12,y:2, direction:'right'},
            {x:11,y:2, direction:'left'},
            {x:10,y:2, direction:'left'},
            {x:9,y:2, direction:'left'},
            {x:8,y:2, direction:'left'},
            {x:7,y:2, direction:'left'},
            {x:6,y:2, direction:'left'},
            {x:5,y:2, direction:'left'},
            {x:4,y:2, direction:'left'},
            {x:3,y:2, direction:'left'},
        ],
    },
]