const initialOnis = [
    {
        x:4,
        y:0,
        pathIndex: 0,
        pathDirection : 1,
        direction: 'back',
        dead: false,
        path: [
            {x:4,y:0},
            {x:4,y:1},
            {x:4,y:2},
            {x:4,y:3},
            {x:4,y:4},
            {x:4,y:5},
            {x:4,y:6},
            {x:4,y:7},
            {x:4,y:8},
            {x:4,y:9},
            {x:4,y:10},
            {x:4,y:11},
            {x:4,y:12},
            {x:4,y:13},
            {x:4,y:14},
            {x:4,y:15},
        ],
    },
    {
        x:3,
        y:0,
        pathIndex: 0,
        direction : 1,
        dead: false,
        path: [
            {x:3,y:0},
            {x:3,y:1},
            {x:3,y:2},
            {x:3,y:3},
            {x:3,y:4},
            {x:3,y:5},
            {x:3,y:6},
            {x:3,y:7},
            {x:3,y:8},
            {x:3,y:9},
            {x:3,y:10},
            {x:3,y:11},
            {x:3,y:12},
            {x:3,y:13},
            {x:3,y:14},
            {x:3,y:15},
        ],
    },
    {
        x:7,
        y:0,
        pathIndex: 0,
        direction : 1,
        dead: false,
        path: [
            {x:7,y:0},
            {x:7,y:1},
            {x:7,y:2},
            {x:7,y:3},
            {x:7,y:4},
            {x:7,y:5},
            {x:7,y:6},
            {x:7,y:7},
            {x:7,y:8},
            {x:7,y:9},
            {x:7,y:10},
            {x:7,y:11},
            {x:7,y:12},
            {x:7,y:13},
            {x:7,y:14},
            {x:7,y:15},
        ],
    },
    {
        x:9,
        y:0,
        pathIndex: 0,
        direction : 1,
        dead: false,
        path: [
            {x:9,y:0},
            {x:9,y:1},
            {x:9,y:2},
            {x:9,y:3},
            {x:9,y:4},
            {x:9,y:5},
            {x:9,y:6},
            {x:9,y:7},
            {x:9,y:8},
            {x:9,y:9},
            {x:9,y:10},
            {x:9,y:11},
            {x:9,y:12},
            {x:9,y:13},
            {x:9,y:14},
            {x:9,y:15},
        ],
    },
    {
        x:12,
        y:0,
        pathIndex: 0,
        direction : 1,
        dead: false,
        path: [
            {x:12,y:0},
            {x:12,y:1},
            {x:12,y:2},
            {x:12,y:3},
            {x:12,y:4},
            {x:12,y:5},
            {x:12,y:6},
            {x:12,y:7},
            {x:12,y:8},
            {x:12,y:9},
            {x:12,y:10},
            {x:12,y:11},
            {x:12,y:12},
            {x:12,y:13},
            {x:12,y:14},
            {x:12,y:15},
        ],
    },
    {
        x:15,
        y:0,
        pathIndex: 0,
        direction : 1,
        dead: false,
        path: [
            {x:15,y:0},
            {x:15,y:1},
            {x:15,y:2},
            {x:15,y:3},
            {x:15,y:4},
            {x:15,y:5},
            {x:15,y:6},
            {x:15,y:7},
            {x:15,y:8},
            {x:15,y:9},
            {x:15,y:10},
            {x:15,y:11},
            {x:15,y:12},
            {x:15,y:13},
            {x:15,y:14},
            {x:15,y:15},
        ],
    }
]